name: DotNet test link dir

on:
  pull_request:
    branches: [force-junction]
  push:
    branches: [force-junction]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  POWERSHELL_TELEMETRY_OPTOUT: 1
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  ## DOTNET_INSTALL_DIR: D:\dotnet

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Test
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10]
        #n: [1]
        os: [windows-2019, windows-2022]
        cache: [false, true]
        #cache: [false]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache NuGet packages
        if: matrix.cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Setup DotNet 8
        uses: akv-platform/setup-dotnet@windows-performance-one-dir
        with:
          dotnet-version: 8.0.x

      - name: DotNet restore
        if: ${{ false }}
        run: |
          dotnet new nugetconfig
          dotnet restore -v n
      
